name: Format Code with Uncrustify using python script

on: [push, pull_request]

jobs:
  format-code:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            cmake \
            gcc \
            g++ \
            curl \
            automake \
            libtool
          
      - name: build uncrustify library
        env:
          BADGE: linux
        run: |
          git clone https://github.com/uncrustify/uncrustify.git
          cd uncrustify
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
          cmake --build . --config Release
      
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Verify Python installation  
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Verify submodule accessibilty
      - name: List files in the submodule
        run: |
          echo "Listing files in the psoc6hal submodule:"
          ls submodules/psoc6hal/include
      
      # Run uncrustify using python script
      - name: Run Python Script
        run: |
          python uncrustify_python_script.py
         
      # Commit files
      - name: Commit formatted files
        run: |
          git config --global user.name "akuma517"
          git config --global user.email "ayush.nith17@gmail.com"
          git add .
          git rm -f --cached uncrustify
          git commit -m "Formatted via Github Actions"

      #push changes to main
      - name: Push changes
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         git push origin main